config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: %i[show edit update]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :address, label: "Address" %>
  <%= f.input :description, label: "Description" %>
  <%= f.input :price_per_night, label: "Price per night" %>
  <%= f.input :number_of_guests, label: "Number of guests" %>
  <%= f.input :url, label: "Url of picture" %>
  <%= f.submit "Add a new flat", class: "btn btn-primary" %>
  <%= link_to "Return to listings", flats_path, class:"btn btn-danger" %>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form', task: @task %>

app/views/flats/index.html.erb
<div class="container d-flex p-2">
<% @flats.each do |flat| %>
  <div class="card-trip">
    <img class="small-image" src=<%= flat.url %> />
    <div class="card-trip-infos">
      <div>
        <h2><%= flat.name %></h2>
        <p><%= flat.address %></p>
      </div>
      <h2 class="card-trip-pricing">$<%= flat.price_per_night %></h2>
    </div>
    <div class="links">
    <%= link_to "More info", flats_path, class:"" %>
    <%= link_to "Edit", flats_path, class:"" %>
    <%= link_to "Remove", flats_path, class:"" %>
  </div>
  </div>
<% end %>
</div>

app/views/flats/new.html.erb
<%= render 'form', task: @task %>

app/views/flats/show.html.erb
<div class="container">
<div class="container d-flex p-0 m-0">
  <div class="card-trip big ml-0">
    <img class="big-image" src=<%= @flat.url %> />
    <div class="card-trip-infos">
      <div>
        <h2><%= @flat.name %></h2>
        <p><%= @flat.address %></p>
        <p><%= @flat.description %></p>
      </div>
      <h2 class="card-trip-pricing">$<%= @flat.price_per_night %></h2>
    </div>
  </div>
</div>
<%= link_to "Return to listings", flats_path, class:"btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</html>

app/views/layouts/navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>